name: macOS and iOS SOFA Scan

on:
  schedule:
    # Run at 5:00 PM, 6:00 PM, 7:00 PM, and 8:00 PM CET on weekdays
    - cron: '0 17-20 * * 1,2,3,4,5'
    
    # Run every day at 4-hour intervals
    - cron: '30 */4 * * *'
  workflow_dispatch:
    inputs:
      pinned_build:
        description: 'Optional pinned macOS build number'
        required: false
        default: ''

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . -t sofa_scan

    - name: Run Docker container with macOS and iOS arguments
      env:
        BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}
      run: |
        # Use the pinned_build input if provided, otherwise fall back to the BUILD_NUMBER variable
        build_arg="${{ github.event.inputs.pinned_build }}"
        if [ -z "$build_arg" ]; then
          build_arg="$BUILD_NUMBER"
        fi
        echo "Using build: $build_arg"
        docker run --name sofa_scan_container \
          -e TIMESTAMP_FILE_PATH=/app/v1/timestamp.json \
          -v $(pwd)/v1:/app/v1 \
          sofa_scan macOS iOS --build "$build_arg"

    - name: Copy resulting JSON files from container to host
      run: |
        docker cp sofa_scan_container:/app/v1/timestamp.json v1/. || echo "Failed to copy timestamp.json"
        docker cp sofa_scan_container:/app/macos_data_feed.json v1/. || true
        docker cp sofa_scan_container:/app/ios_data_feed.json v1/. || true
        docker cp sofa_scan_container:/app/rss_feed.xml v1/. || true
        docker cp sofa_scan_container:/app/cache . || echo "Failed to copy cache files"
        docker cp sofa_scan_container:/app/time-series.csv .

    - name: List contents of v1
      run: ls -la v1/

    - name: Commit and push if changes are detected
      run: |
        timestamp=$(date +'%Y-%m-%d %H:%M:%S')
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add v1/*.json v1/*.xml cache/*.json time-series.csv
        git commit -m "Update SOFA data - $timestamp" -a || exit 0
        git push
